### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by huangk3** [dcroote/singlecell-ige#1]
Hi @dcroote ,

I was trying to run the pipeline on my Mac, and ran into an error. I wondered if there is any clue about this error. Thanks!

% snakemake --use-conda  --cores 4 
Multiple include of /Users/kh/Softwares/singlecell-ige/rules/common.smk ignored
Building DAG of jobs...
Traceback (most recent call last):
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/site-packages/snakemake/__init__.py", line 647, in snakemake
    keepincomplete=keep_incomplete,
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/site-packages/snakemake/workflow.py", line 777, in execute
    quiet=list_conda_envs,
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/site-packages/snakemake/dag.py", line 260, in create_conda_envs
    env.create(dryrun)
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/site-packages/snakemake/deployment/conda.py", line 232, in create
    conda = Conda(self._container_img)
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/site-packages/snakemake/deployment/conda.py", line 343, in __new__
    inst.__init__(container_img=container_img)
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/site-packages/snakemake/deployment/conda.py", line 357, in __init__
    self.info = json.loads(shell.check_output(self._get_cmd("conda info --json")))
  File "/Users/kh/Softwares/mambaforge/envs/IgE_snakemake/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by dcroote** [comment]
Hi @huangk3 - I think it may have to do with the snakemake version. Can you provide the output of the following:
```
snakemake --version
conda --version
```

**Comment by huangk3** [comment]
Thanks for the response @dcroote. Here is the version info:

% snakemake --version 
5.11.1
% conda --version 
conda 4.10.3

**Comment by dcroote** [comment]
Thanks @huangk3, I was able to reproduce your error with snakemake `5.11.1`. Can you please downgrade to snakemake `5.2.4`? If you created the `conda` env via the instructions in the readme, you should be able to do this via `conda remove -y snakemake-minimal && conda install -y snakemake-minimal=5.2.4`.

**Comment by huangk3** [comment]
The error is gone after installed snakemake v5.2.4. Thanks for the help! @dcroote
